Repository valkey-io/valkey, pull requests merged in 2024-05, with the labels that each got.

#350 CRC64 perf improvements from Redis patches
  src/Makefile
  src/crc64.c
  src/crccombine.c
  src/crccombine.h
  src/crcspeed.c
  src/crcspeed.h
Labels: release-notes

#393 Rename redis in aof logs and proc title redis-aof-rewrite to valkey-aof-rewrite.
  src/aof.c
  src/cluster_legacy.c
Labels: release-notes, rebranding, breaking-change

#389 Changed links and naming to valkey instead of redis
  00-RELEASENOTES
  MANIFESTO
  deps/README.md
  deps/linenoise/README.markdown
  src/commands/README.md
Labels: rebranding

#430 Log the real reason for why posix_fadvise failed
  src/util.c
Labels: release-notes

#433 Update links in module API docs (generated from module.c)
  src/module.c
  utils/generate-module-api-doc.rb
Labels: rebranding

#221 Pin versions of Github Actions in CI
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverity.yml
  .github/workflows/daily.yml
  .github/workflows/external.yml
  .github/workflows/reply-schemas-linter.yml
  .github/workflows/spell-check.yml
Labels: to-be-merged

#436 Fix issues for older versions of Darwin and improve PowerPC support
  src/config.h
  src/debug.c
Labels: release-notes

#324 Add noscores option to command ZSCAN.
  src/commands.def
  src/commands/zscan.json
  src/db.c
  tests/unit/scan.tcl
Labels: release-notes, major-decision-approved, needs-doc-pr

#468 Prevent clang-format in certain places
  src/.clang-format-ignore
  src/acl.c
  src/aof.c
  src/asciilogo.h
  src/eval.c
  src/functions.c
  src/latency.c
  src/listpack.c
  src/module.c
  src/networking.c
  src/notify.c
  src/object.c
  src/replication.c
  src/resp_parser.c
  src/sds.c
  src/sentinel.c
  src/server.c
  src/slowlog.c
  src/t_stream.c
  src/t_string.c
  src/util.c
  src/valkey-benchmark.c
  src/valkey-cli.c
  src/ziplist.c
Labels: needs-doc-pr

#501 Finish postponed SCAN changes
  src/db.c
  tests/unit/scan.tcl
Labels: release-notes, breaking-change

#53 Cache CLUSTER SLOTS response for improving throughput and reduced latency.
  src/cluster.c
  src/cluster.h
  src/cluster_legacy.c
  src/cluster_legacy.h
  src/config.c
  src/connection.h
  src/networking.c
  src/server.h
  tests/cluster/tests/04-resharding.tcl
  tests/unit/cluster/announced-endpoints.tcl
  tests/unit/cluster/failover.tcl
  tests/unit/cluster/manual-failover.tcl
Labels: performance

#536 Undeprecate cluster slots command
  src/commands.def
  src/commands/cluster-slots.json
Labels: release-notes, major-decision-approved, needs-doc-pr

#495 Make cluster replicas return ASK and TRYAGAIN
  src/cluster.c
  tests/unit/cluster/slot-migration.tcl
Labels: release-notes

#490 Introduce C11 _Atomics
  src/aof.c
  src/bio.c
  src/db.c
  src/evict.c
  src/functions.c
  src/lazyfree.c
  src/module.c
  src/networking.c
  src/rdb.c
  src/replication.c
  src/server.c
  src/server.h
  src/threads_mngr.c
  src/valkey-benchmark.c
  src/zmalloc.c
Labels: release-notes

#258 Introduce shared query buffer for client reads
  src/networking.c
  src/replication.c
  src/server.c
  src/server.h
  tests/unit/introspection.tcl
  tests/unit/querybuf.tcl
Labels: release-notes, to-be-merged

#118 Change BITCOUNT 'end' as optional like BITPOS
  src/bitops.c
  src/commands.def
  src/commands/bitcount.json
  tests/unit/bitops.tcl
Labels: enhancement, release-notes, major-decision-approved

#526 Fix crash where command duration is not reset when client is blocked …
  src/server.c
  tests/unit/cluster/slot-migration.tcl
Labels: bug, release-notes
