Repository valkey-io/valkey, pull requests merged in 2024-06, with the labels that each got.

#250 Unshare object to avoid LRU/LFU being messed up.
  src/db.c
  src/object.c
  src/server.h
  tests/unit/maxmemory.tcl
Labels: bug, release-notes

#502 Adjust sds types
  src/sds.c
  src/sdsalloc.h
  src/unit/test_files.h
  src/unit/test_sds.c
Labels: release-notes, performance

#608 module: fix typo in `REGISTER_API`
  src/module.c
Labels: release-notes

#598 Replace masteruser and masterauth with primaryuser and primaryauth
  src/config.c
  src/valkey-cli.c
  tests/integration/valkey-benchmark.tcl
  tests/sentinel/tests/03-runtime-reconf.tcl
  tests/unit/auth.tcl
  tests/unit/slowlog.tcl
  valkey.conf
Labels: release-notes, major-decision-pending, de-crapify

#596 Allow CLUSTER NODES/INFO/MYID/MYSHARDID during loading state
  src/commands.def
  src/commands/cluster-info.json
  src/commands/cluster-myid.json
  src/commands/cluster-myshardid.json
  src/commands/cluster-nodes.json
Labels: release-notes, major-decision-approved

#636 Make configs dir/dbfilename/cluster-config-file reject empty string
  src/config.c
Labels: release-notes

#615 Format yaml files
  .config/format.yml
  .github/dependabot.yml
  .github/workflows/build-release-packages.yml
  .github/workflows/call-build-linux-arm-packages.yml
  .github/workflows/call-build-linux-x86-packages.yml
  .github/workflows/ci.yml
  .github/workflows/clang-format.yml
  .github/workflows/codecov.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverity.yml
  .github/workflows/daily.yml
  .github/workflows/external.yml
  codecov.yml
Labels: de-crapify

#461 Make cluster meet reliable under link failures
  src/cluster_legacy.c
  src/debug.c
  src/server.h
  tests/unit/cluster/cluster-multiple-meets.tcl
  tests/unit/cluster/cluster-reliable-meet.tcl
Labels: cluster, release-notes

#634 Only primary with slots has the right to mark a node as failed
  src/cluster_legacy.c
  tests/unit/cluster/failure-marking.tcl
Labels: cluster, release-notes

#665 Support RDB compatability with Redis 7.2.4 RDB format
  src/rdb.c
  src/rdb.h
  src/valkey-check-rdb.c
Labels: release-notes, major-decision-approved

#617 Add new SCRIPT SHOW subcommand to dump script via sha1
  src/commands.def
  src/commands/script-show.json
  src/eval.c
  src/server.c
  tests/unit/scripting.tcl
Labels: release-notes, major-decision-approved

#453 Add zfree_with_size to optimize sdsfree since we can get zmalloc_size from the header
  src/sds.c
  src/sdsalloc.h
  src/zmalloc.c
  src/zmalloc.h
Labels: release-notes, performance

#325 replica redirect read&write to primary in standalone mode
  src/cluster.c
  src/commands.def
  src/commands/client-capa.json
  src/networking.c
  src/server.c
  src/server.h
  tests/integration/replica-redirect.tcl
Labels: release-notes, major-decision-approved, needs-doc-pr

#700 Upstream the availability zone info string from KeyDB
  src/config.c
  src/server.c
  src/server.h
  valkey.conf
Labels: release-notes, major-decision-approved

#351 Introduce CLUSTER SLOT-STATS command (#20).
  src/Makefile
  src/cluster.h
  src/cluster_slot_stats.c
  src/commands.def
  src/commands/cluster-slot-stats.json
  src/server.h
  tests/unit/cluster/slot-stats.tcl
Labels: release-notes, major-decision-approved, needs-doc-pr

#705 Very minor misspelling in some tests
  tests/unit/cluster/slot-migration.tcl
Labels: polish, pending-missing-dco
