Repository valkey-io/valkey, pull requests merged in 2024-07, with the labels that each got.

#693 Allow Module authentication to succeed when cluster is down
  src/cluster.c
  tests/unit/moduleapi/cluster.tcl
Labels: release-notes

#674 Introduce thread-local storage variable to update thread's own used_memory and sum when reading to reduce atomic contention.
  src/config.h
  src/networking.c
  src/zmalloc.c
Labels: release-notes

#541 Embed key into dict entry
  src/db.c
  src/debug.c
  src/defrag.c
  src/dict.c
  src/dict.h
  src/kvstore.c
  src/kvstore.h
  src/object.c
  src/rdb.c
  src/sds.c
  src/sds.h
  src/server.c
Labels: release-notes, major-decision-approved, performance

#723 Nested MULTI or WATCH in MULTI now will abort the transaction
  src/commands.def
  src/commands/multi.json
  src/commands/watch.json
  src/multi.c
  tests/unit/multi.tcl
Labels: release-notes, breaking-change

#736 Dual stack and client-specific IPs in cluster
  src/cluster.c
  src/cluster.h
  src/cluster_legacy.c
  src/cluster_legacy.h
  src/config.c
  src/connection.h
  src/module.c
  src/networking.c
  src/server.h
  src/valkeymodule.h
  tests/support/cluster_util.tcl
  tests/support/server.tcl
  tests/unit/cluster/announce-client-ip.tcl
  valkey.conf
Labels: cluster, release-notes, needs-doc-pr

#738 Configurable cluster blacklist TTL
  src/cluster_legacy.c
  src/config.c
  src/server.h
  valkey.conf
Labels: major-decision-approved

#500 Limit tracking custom errors (e.g. from LUA) while allowing non custom errors to be tracked normally
  src/networking.c
  src/script_lua.c
  src/server.c
  src/server.h
  tests/unit/info.tcl
Labels: release-notes, major-decision-approved, needs-doc-pr

#477 Introduce Valkey Over RDMA transport (experimental)
  .github/workflows/ci.yml
  .gitignore
  README.md
  runtest-rdma
  src/Makefile
  src/rdma.c
  tests/rdma/Makefile
  tests/rdma/rdma-test.c
  tests/rdma/rdma_env.py
  tests/rdma/run.py
Labels: major-decision-approved

#647 Replace master-reboot-down-after-period with primary-reboot-down-after-period in sentinel.conf
  sentinel.conf
  src/sentinel.c
  tests/sentinel/tests/12-master-reboot.tcl
Labels: de-crapify

#60 Dual channel replication
  src/config.c
  src/debug.c
  src/networking.c
  src/rdb.c
  src/replication.c
  src/rio.c
  src/rio.h
  src/server.c
  src/server.h
  tests/helpers/bg_server_sleep.tcl
  tests/helpers/gen_write_load.tcl
  tests/integration/dual-channel-replication.tcl
  tests/integration/psync2-master-restart.tcl
  tests/integration/replication-buffer.tcl
  tests/integration/replication-psync.tcl
  tests/integration/replication.tcl
  tests/support/test.tcl
  tests/support/util.tcl
  tests/unit/auth.tcl
  tests/unit/introspection.tcl
  valkey.conf
Labels: major-decision-approved

#763 Io thread work offload
  src/ae.c
  src/ae.h
  src/db.c
  src/dict.c
  src/dict.h
  src/io_threads.c
  src/io_threads.h
  src/module.c
  src/networking.c
  src/server.c
  src/server.h
Labels: release-notes

#782 Optimize failover time when the new primary node is down again
  src/cluster_legacy.c
  tests/support/util.tcl
  tests/unit/cluster/failover2.tcl
Labels: release-notes

#807 Typo fix in hyperloglog.c
  src/hyperloglog.c
Labels: polish

#815 Added a flag to run additional tests for additional tests
  .github/workflows/daily.yml
Labels: run-extra-tests

#712 Add cpu-usec metric support under CLUSTER SLOT-STATS command (#20).
  src/blocked.c
  src/cluster.c
  src/cluster.h
  src/cluster_legacy.c
  src/cluster_legacy.h
  src/cluster_slot_stats.c
  src/cluster_slot_stats.h
  src/commands/cluster-slot-stats.json
  src/config.c
  src/script.c
  src/server.c
  src/server.h
  tests/unit/cluster/slot-stats.tcl
  valkey.conf
Labels: release-notes

#762 Replicas with the same offset queue up for election
  src/cluster_legacy.c
  tests/support/util.tcl
  tests/unit/cluster/failover.tcl
Labels: release-notes

#823 Improve CPU usage in tests with IO threads
  src/io_threads.c
Labels: run-extra-tests

#720 Add network-bytes-in and network-bytes-out metric support under CLUSTER SLOT-STATS command (#20)
  src/cluster_legacy.h
  src/cluster_slot_stats.c
  src/cluster_slot_stats.h
  src/commands/cluster-slot-stats.json
  src/db.c
  src/networking.c
  src/pubsub.c
  src/replication.c
  src/server.c
  src/server.h
  tests/unit/cluster/slot-stats.tcl
Labels: release-notes

#840 Handle underflow condition of network out slot stats metric
  src/cluster_slot_stats.c
  src/cluster_slot_stats.h
  src/replication.c
Labels: run-extra-tests

#834 Fix bug in writeToClient
  src/networking.c
Labels: pending-missing-dco
