Repository valkey-io/valkey, pull requests merged in 2024-09, with the labels that each got.

#913 Change all the lazyfree configurations to yes by default
  src/config.c
  tests/unit/expire.tcl
  tests/unit/latency-monitor.tcl
  tests/unit/maxmemory.tcl
  tests/unit/memefficiency.tcl
  tests/unit/moduleapi/async_rm_call.tcl
  tests/unit/moduleapi/cluster.tcl
  tests/unit/moduleapi/postnotifications.tcl
  tests/unit/moduleapi/propagate.tcl
  tests/unit/type/list.tcl
  valkey.conf
Labels: release-notes, major-decision-approved, run-extra-tests

#877 Add configuration hide-user-data-from-log to hide user data from server logs
  src/acl.c
  src/config.c
  src/debug.c
  src/networking.c
  src/replication.c
  src/server.h
  tests/assets/default.conf
  valkey.conf
Labels: release-notes, major-decision-approved, run-extra-tests

#983 Rewrite lazyfree docs in valkey.conf to reflect that lazy is now default
  valkey.conf
Labels: documentation

#965 Fix cluster replica unable to establish replication link in race condition
  src/cluster_legacy.c
Labels: release-notes

#886 Fix aof base suffix when modifying aof-use-rdb-preamble during rewrite
  src/aof.c
  src/server.h
  tests/integration/aof-multi-part.tcl
Labels: release-notes

#875 Add client info to SHUTDOWN / CLUSTER FAILOVER logs
  src/cluster_legacy.c
  src/db.c
  src/debug.c
  src/server.c
  src/server.h
Labels: release-notes

#949 Migrate listpack.c unit tests to new framework
  src/listpack.c
  src/listpack.h
  src/server.c
  src/unit/test_files.h
  src/unit/test_listpack.c
Labels: run-extra-tests

#946 Migrate dict.c unit tests to new framework
  src/dict.c
  src/dict.h
  src/server.c
  src/unit/test_dict.c
  src/unit/test_files.h
Labels: run-extra-tests

#778 For MEETs, save the extensions support flag immediately during MEET processing
  src/cluster_legacy.c
Labels: run-extra-tests

#1001 Fix module RdbLoad wrongly disable the AOF
  src/module.c
  tests/unit/moduleapi/rdbloadsave.tcl
Labels: bug, release-notes

#1016 Improve stability of hostnames test
  tests/unit/cluster/hostnames.tcl
Labels: test-failure

#1024 Re-enable empty-shard slot migration tests
  tests/unit/cluster/slot-migration.tcl
Labels: run-extra-tests

#822 Trigger a save of the cluster configuration file before shutting down
  src/cluster.h
  src/cluster_legacy.c
  src/server.c
Labels: release-notes

#981 Fix replica unable trigger migration when it received CLUSTER SETSLOT in advance
  src/cluster_legacy.c
  src/networking.c
  src/replication.c
  src/server.h
  tests/unit/cluster/replica-migration.tcl
Labels: release-notes, run-extra-tests

#943 Improve code readability in dict.c
  src/dict.c
  src/unit/test_dict.c
Labels: run-extra-tests

#926 Replica flush the old data after RDB file is ok in disk-based replication
  src/replication.c
  tests/integration/replication.tcl
Labels: release-notes

#1040 Fix default value of primary-reboot-down-after-period in sentinel.conf
  sentinel.conf
Labels: release-notes

#1053 Use _Thread_local to solve threads.h build issue
  src/zmalloc.c
Labels: release-notes

#1063 Fix module / script call CLUSTER SLOTS / SHARDS fake client check crash
  src/aof.c
  src/eval.c
  src/functions.c
  src/module.c
  src/networking.c
  src/server.h
  tests/integration/aof.tcl
  tests/modules/Makefile
  tests/modules/cluster.c
  tests/unit/cluster/scripting.tcl
  tests/unit/moduleapi/cluster.tcl
Labels: run-extra-tests

#1074 Fix RDMA build dependence
  src/Makefile
Labels: bug
