Repository valkey-io/valkey, pull requests merged in 2024-12, with the labels that each got.

#1149 Reset repl_down_since to zero only on state change
  src/replication.c
Labels: release-notes

#905 Free strings during BGSAVE/BGAOFRW to reduce copy-on-write
  src/object.c
  src/rdb.c
Labels: release-notes

#1293 Optimize PFCOUNT, PFMERGE command by SIMD acceleration
  src/config.h
  src/hyperloglog.c
  tests/unit/hyperloglog.tcl
Labels: release-notes, performance

#1242 Refactor of ActiveDefrag to reduce latencies
  src/ae.c
  src/config.c
  src/defrag.c
  src/dict.c
  src/dict.h
  src/kvstore.c
  src/kvstore.h
  src/server.c
  src/server.h
  tests/unit/memefficiency.tcl
  tests/unit/moduleapi/defrag.tcl
  valkey.conf
Labels: release-notes, major-decision-approved

#1041 Add API UpdateRuntimeArgs for updating the module arguments during runtime
  src/module.c
  src/valkeymodule.h
  tests/modules/Makefile
  tests/modules/moduleparameter.c
  tests/unit/moduleapi/moduleconfigs.tcl
Labels: major-decision-approved

#1386 RDMA: Fix dead loop when transfer large data (20KB)
  src/rdma.c
Labels: release-notes

#1403 Fix Module Update Args test when other modules are loaded
  tests/unit/moduleapi/moduleconfigs.tcl
Labels: run-extra-tests

#1402 Fix sanitizer builds with clang
  src/unit/test_networking.c
Labels: run-extra-tests

#1317 Allow `MEMORY MALLOC-STATS` and `MEMORY PURGE` during loading phase
  src/commands.def
  src/commands/memory-malloc-stats.json
  src/commands/memory-purge.json
  tests/unit/introspection.tcl
Labels: release-notes, major-decision-approved

#1389 Optimize ZRANK to avoid path comparisons
  src/server.h
  src/t_zset.c
Labels: release-notes, performance

#1324 Set Command with IFEQ Support
  src/commands.def
  src/commands/set.json
  src/t_string.c
  tests/assets/test_cli_hint_suite.txt
  tests/unit/type/string.tcl
Labels: release-notes, major-decision-approved, to-be-merged, client-changes-needed

#1398 Add new flag in `CLIENT LIST` for import-source client
  src/config.c
  src/networking.c
  tests/unit/expire.tcl
Labels: release-notes, major-decision-approved, needs-doc-pr

#1429 Fix Valkey binary build workflow, version support changes.
  .github/workflows/call-build-linux-x86-packages.yml
  utils/releasetools/build-config.json
Labels: release-notes

#1176 Replace dict with new hashtable for sets datatype
  src/db.c
  src/debug.c
  src/defrag.c
  src/hashtable.c
  src/hashtable.h
  src/lazyfree.c
  src/module.c
  src/object.c
  src/rdb.c
  src/server.c
  src/server.h
  src/t_set.c
  src/t_zset.c
  src/zmalloc.c
  src/zmalloc.h
  tests/unit/info.tcl
  tests/unit/type/set.tcl
Labels: release-notes, performance, run-extra-tests

#1356 Automatic failover vote is not limited by two times the node timeout
  src/cluster_legacy.c
  src/cluster_legacy.h
  tests/unit/cluster/manual-failover.tcl
Labels: release-notes

#1277 Adds support for scripting engines as Valkey modules
  src/function_lua.c
  src/functions.c
  src/functions.h
  src/module.c
  src/module.h
  src/script.h
  src/script_lua.c
  src/script_lua.h
  src/util.c
  src/util.h
  src/valkeymodule.h
  tests/modules/CMakeLists.txt
  tests/modules/Makefile
  tests/modules/helloscripting.c
  tests/unit/functions.tcl
  tests/unit/moduleapi/scriptingengine.tcl
Labels: release-notes, major-decision-approved, to-be-merged, needs-doc-pr
