Repository valkey-io/valkey, pull requests merged in 2024-08, with the labels that each got.

#805 Correctly recode client infomation to the slowlog when runing script
  src/server.c
  tests/unit/slowlog.tcl
Labels: release-notes

#837 Fix dual-channel-replication related issues
  src/networking.c
  src/rdb.c
  src/replication.c
  tests/integration/dual-channel-replication.tcl
Labels: run-extra-tests

#883 Fix crash in active defrag
  src/defrag.c
Labels: release-notes

#829 Optimize ZUNION[STORE] command by removing unnecessary accumulator dict
  src/t_zset.c
Labels: release-notes, performance

#871 To avoid bouncing -REDIRECT during FAILOVER
  src/server.c
  tests/integration/replica-redirect.tcl
Labels: needs-doc-pr

#907 Prevent later accesses to unallocated memory
  src/valkey-cli.c
Labels: bug, cluster

#764 Skip tracking clients OOM test when I/O threads are enabled
  .github/workflows/daily.yml
  tests/support/server.tcl
  tests/test_helper.tcl
  tests/unit/info.tcl
  tests/unit/maxmemory.tcl
  tests/unit/memefficiency.tcl
Labels: bug, pending-missing-dco

#884 Avoid to re-establish replication if node is already myself primary in CLUSTER REPLICATE
  src/cluster_legacy.c
Labels: release-notes

#759 Decline unsubscribe related command in non-subscribed mode
  src/server.c
  tests/unit/info.tcl
  tests/unit/pubsub.tcl
  tests/unit/pubsubshard.tcl
Labels: breaking-change

#934 Revert repl backlog size back to 1mb for dual channel tests
  tests/integration/dual-channel-replication.tcl
Labels: run-extra-tests

#879 Fix CLUSTER SETSLOT block and unblock error when all replicas are down
  src/cluster_legacy.c
  tests/unit/cluster/slot-migration.tcl
Labels: release-notes

#928 valkey-cli make source node ignores NOREPLICAS when doing the last CLUSTER SETSLOT
  src/valkey-cli.c
  tests/unit/cluster/replica-migration.tcl
Labels: release-notes

#935 Remove accurate from extra test tag
  .github/workflows/daily.yml
Labels: run-extra-tests

#901 Add support for setting the group on a unix domain socket
  src/anet.c
  src/anet.h
  src/config.c
  src/connection.h
  src/rdma.c
  src/server.c
  src/server.h
  src/unix.c
  tests/unit/introspection.tcl
  tests/unit/other.tcl
  valkey.conf
Labels: release-notes, major-decision-approved

#861 Improve multithreaded performance with memory prefetching
  src/Makefile
  src/config.c
  src/config.h
  src/dict.c
  src/dict.h
  src/fmtargs.h
  src/io_threads.c
  src/kvstore.c
  src/kvstore.h
  src/memory_prefetch.c
  src/memory_prefetch.h
  src/networking.c
  src/server.c
  src/server.h
  tests/unit/networking.tcl
  utils/generate-fmtargs.py
  valkey.conf
Labels: release-notes, run-extra-tests

#923 Use sdsAllocSize instead of sdsZmallocSize
  src/debug.c
  src/eval.c
  src/functions.c
  src/networking.c
  src/object.c
  src/sds.c
  src/server.c
  src/server.h
Labels: performance, run-extra-tests

#860 Move prepareClientToWrite out of loop for lrange command to reduce the redundant call.
  src/networking.c
  src/server.h
  src/t_list.c
Labels: performance

#846 Using intrinsics to optimize counting HyperLogLog trailing bits
  src/hyperloglog.c
  src/intrinsics.h
Labels: run-extra-tests

#958 Delete files MANIFESTO, BUGS and INSTALL
  BUGS
  INSTALL
  MANIFESTO
Labels: documentation, de-crapify

#960 Delete TLS.md and update README.md about tests
  README.md
  TLS.md
  tests/README.md
Labels: documentation

#961 free client's multi state when it becomes dirty
  src/multi.c
Labels: release-notes

#944 Fix reconfiguring sub-replica causing data loss when myself change shard_id
  src/cluster_legacy.c
  tests/unit/cluster/replica-migration.tcl
Labels: run-extra-tests

#895 standalone -REDIRECT handles special case of MULTI context
  src/server.c
  tests/integration/replica-redirect.tcl
  tests/unit/cluster/transactions-on-replica.tcl
Labels: needs-doc-pr

#973 Delete unused parts of zipmap
  src/unit/test_files.h
  src/unit/test_zipmap.c
  src/zipmap.c
  src/zipmap.h
Labels: run-extra-tests

#865 Fast path in SET if the expiration time is expired
  src/cluster.c
  src/db.c
  src/expire.c
  src/server.h
  src/t_string.c
  tests/unit/type/string.tcl
Labels: release-notes, run-extra-tests
