Repository valkey-io/valkey, pull requests merged in 2024-10, with the labels that each got.

#1092 Creates an empty lua table with specified initial capacity as much as possible
  src/script_lua.c
Labels: release-notes, performance

#1100 Update keyspace notifications link to valkey.io in code comment
  src/notify.c
Labels: polish

#1077 Avoid timing issue in diskless-load-swapdb test
  tests/unit/cluster/diskless-load-swapdb.tcl
Labels: test-failure

#688 Rax size tracking
  .config/typos.toml
  src/module.c
  src/object.c
  src/rax.c
  src/rax.h
  src/rax_malloc.h
  src/unit/test_files.h
  src/unit/test_rax.c
Labels: release-notes

#909 Add flush-before-load option for repl-diskless-load
  src/config.c
  src/replication.c
  src/server.h
  tests/integration/replication.tcl
  valkey.conf
Labels: release-notes, major-decision-approved

#1140 Fix empty response for ACL CAT category subcommand for module defined categories
  src/acl.c
  tests/unit/moduleapi/aclcheck.tcl
Labels: release-notes

#1142 Fix typo last_procssed -> last_processed
  src/server.c
Labels: polish

#1119 Move prepareClientToWrite out of loop for HGETALL command
  src/networking.c
  src/server.h
  src/t_hash.c
Labels: release-notes, performance

#977 Take hz into account in activerehashing to avoid CPU spikes
  src/server.c
  src/server.h
  valkey.conf
Labels: release-notes, major-decision-approved

#945 Refactor return and goto statements
  src/replication.c
  src/server.h
Labels: run-extra-tests

#1168 Improved hashing algorithm in luaS_newlstr
  deps/README.md
  deps/lua/src/lstring.c
Labels: release-notes, performance

#1155 Add 'WithDictIndex' expiry API and update RANDOMKEY command
  src/db.c
  tests/unit/multi.tcl
Labels: release-notes

#1182 Fix SORT GET to ignore special pattern # in cluster slot check
  src/db.c
  src/sort.c
  tests/unit/sort.tcl
Labels: release-notes

#757 Introduce bgsave cancel
  src/commands.def
  src/commands/bgsave.json
  src/rdb.c
  tests/integration/rdb.tcl
Labels: release-notes, major-decision-approved, needs-doc-pr

#1190 Make replica CLUSTER RESET flush async based on lazyfree-lazy-user-flush
  src/cluster_legacy.c
  valkey.conf
Labels: release-notes

#1213 Trim free space from inline command argument strings to avoid excess memory usage
  src/networking.c
Labels: bug, release-notes

#1022 Configurable log and timestamp formats (logfmt, ISO8601)
  src/config.c
  src/server.c
  src/server.h
Labels: major-decision-approved

#1224 fix typo in valkey.conf file's shutdown section
  valkey.conf
Labels: polish

#1220 Increase the IO_THREADS_MAX_NUM.
  src/config.c
  src/config.h
Labels: major-decision-pending

#1230 Improve performance of sdssplitargs
  src/sds.c
  src/unit/test_files.h
  src/unit/test_sds.c
Labels: performance
