Repository valkey-io/valkey, pull requests merged in 2024-04, with the labels that each got.

#103 Fine-tune ASCII art
  src/asciilogo.h
Labels: polish

#127 Update coverity to reflect project name
  .github/workflows/coverity.yml
Labels: polish

#133 Fix rename redis to valkey to pass reply-schemas-validator job
  utils/req-res-log-validator.py
Labels: trademark-review

#29 Remove trademarked wording on configuration file and individual configs
  .gitignore
  sentinel.conf
  src/acl.c
  src/config.c
  src/module.c
  src/server.c
  src/server.h
  tests/support/server.tcl
  tests/test_helper.tcl
  tests/unit/other.tcl
  utils/install_server.sh
  utils/systemd-redis_server.service
  valkey.conf
Labels: release-notes, trademark-review

#47 Update versioning fields for compatibility
  src/cli_common.c
  src/config.c
  src/debug.c
  src/lolwut.c
  src/lolwut5.c
  src/lolwut6.c
  src/mkreleasehdr.sh
  src/module.c
  src/networking.c
  src/rdb.c
  src/script_lua.c
  src/sentinel.c
  src/server.c
  src/version.h
  tests/unit/moduleapi/misc.tcl
Labels: major-decision-pending

#113 Rename output from redis-* to valkey-* for binaries of "--help" "--version"
  src/server.c
  src/valkey-benchmark.c
  src/valkey-check-aof.c
  src/valkey-check-rdb.c
  src/valkey-cli.c
Labels: trademark-review

#106 Update Makefile comments to relect name change
  src/Makefile
Labels: trademark-review

#213 Adding server.call/pcall option to LUA scripting. (#136)
  src/eval.c
  src/function_lua.c
  src/script_lua.c
  src/script_lua.h
  tests/unit/scripting.tcl
Labels: trademark-review

#193 Add redis symlinks at the same place as the installed binaries
  README.md
  src/Makefile
  src/server.c
Labels: release-notes

#244 Fix: Typo clock_getting -> clock_gettime
  src/monotonic.c
Labels: pending-missing-dco

#265 Maintain determinstic ordering of replica(s) in CLUSTER SLOTS response
  src/cluster_legacy.c
Labels: release-notes

#266 Remove single node cluster validation check from benchmark
  src/valkey-benchmark.c
Labels: release-notes

#259 Rename redis.info to valkey.info in LCOV
  src/.gitignore
  src/Makefile
Labels: trademark-review

#284 Rename macros in valkey-cli.c and redis_strlcpy to valkey
  src/anet.c
  src/cluster_legacy.c
  src/config.c
  src/fmacros.h
  src/module.c
  src/rdb.c
  src/strl.c
  src/util.c
  src/util.h
  src/valkey-cli.c
Labels: rebranding

#282 Correcting the installed redis symlinks in 7.2.4-rc1
  src/Makefile
Labels: bug

#231 update valkey in serverLog messeges in server.c file
  src/server.c
Labels: breaking-change

#206 Remove 'Redis' in error replies
  src/acl.c
  src/config.c
  src/replication.c
  src/script.c
  src/script_lua.c
  tests/unit/acl.tcl
  tests/unit/scripting.tcl
Labels: release-notes, major-decision-approved, breaking-change

#226 Change Redis to Valkey in log messages
  src/acl.c
  src/cluster_legacy.c
  src/eval.c
  src/version.h
Labels: rebranding

#390 Change default syslog-ident from redis to valkey
  src/config.c
  valkey.conf
Labels: release-notes, rebranding, breaking-change

#378 Change default pidfile from redis.pid to valkey.pid
  src/server.h
  tests/assets/default.conf
  tests/assets/minimal.conf
  valkey.conf
Labels: release-notes, rebranding

#345 Initial PR outlining the governance for the project
  CONTRIBUTING.md
  GOVERNANCE.md
  MAINTAINERS.md
Labels: major-decision-approved
