Repository valkey-io/valkey, pull requests merged in 2024-11, with the labels that each got.

#1078 Try to stabilize the failover call in the slot migration test
  tests/support/cluster_util.tcl
  tests/unit/cluster/slot-migration.tcl
Labels: test-failure

#1265 Revert "Decline unsubscribe related command in non-subscribed mode"
  src/server.c
  tests/unit/info.tcl
  tests/unit/pubsub.tcl
  tests/unit/pubsubshard.tcl
Labels: release-notes, major-decision-approved

#1009 Fix replica not able to initate election in time when epoch fails
  src/cluster_legacy.c
  tests/unit/cluster/failover2.tcl
Labels: release-notes, run-extra-tests

#515 Migrate quicklist unit test to new framework
  .github/workflows/daily.yml
  src/Makefile
  src/quicklist.c
  src/quicklist.h
  src/server.c
  src/unit/test_files.h
  src/unit/test_quicklist.c
Labels: run-extra-tests

#1271 Improvements for TLS with I/O threads
  src/tls.c
Labels: release-notes, performance

#1310 Fix LRU crash when getting too many random lua scripts
  src/eval.c
Labels: release-notes, run-extra-tests

#1185 Import-mode: Avoid expiration and eviction during data syncing
  src/commands.def
  src/commands/client-import-source.json
  src/config.c
  src/db.c
  src/evict.c
  src/expire.c
  src/networking.c
  src/server.c
  src/server.h
  tests/unit/expire.tcl
  tests/unit/maxmemory.tcl
  valkey.conf
Labels: release-notes, major-decision-approved, needs-doc-pr

#1266 Remove valkey specific changes in jemalloc source code
  cmake/Modules/SourceFiles.cmake
  deps/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_c.h
  deps/jemalloc/include/jemalloc/jemalloc_macros.h.in
  deps/jemalloc/src/jemalloc.c
  src/Makefile
  src/allocator_defrag.c
  src/allocator_defrag.h
  src/defrag.c
  src/server.c
  src/server.h
  src/zmalloc.c
  src/zmalloc.h
Labels: release-notes

#1274 Make manual failover reset the on-going election to promote failover
  src/cluster_legacy.c
  tests/unit/cluster/manual-failover.tcl
Labels: release-notes, run-extra-tests

#1260 Integrating fast_float to optionally replace strtod
  .github/workflows/ci.yml
  .github/workflows/daily.yml
  deps/Makefile
  deps/README.md
  deps/fast_float/fast_float.h
  deps/fast_float_c_interface/Makefile
  deps/fast_float_c_interface/fast_float_strtod.cpp
  src/Makefile
  src/debug.c
  src/resp_parser.c
  src/sort.c
  src/t_zset.c
  src/unit/test_files.h
  src/unit/test_valkey_strtod.c
  src/util.c
  src/valkey-cli.c
  src/valkey_strtod.h
  tests/test_helper.tcl
Labels: enhancement, major-decision-approved, performance, run-extra-tests

#1209 RDMA builtin support
  README.md
  cmake/Modules/SourceFiles.cmake
  cmake/Modules/ValkeySetup.cmake
  src/CMakeLists.txt
  src/Makefile
  src/config.c
  src/connection.c
  src/connection.h
  src/rdma.c
  src/server.c
  src/server.h
  src/socket.c
  src/tls.c
  src/unix.c
  tests/rdma/run.py
  tests/unit/introspection.tcl
  valkey.conf
Labels: release-notes, major-decision-approved
