Repository valkey-io/valkey, pull requests merged in 2025-04, with the labels that each got.

#1559 In LOLWUT's reply, change "Redis ver." to "Valkey ver."
  src/lolwut.c
  src/lolwut5.c
  src/lolwut6.c
  src/script.c
  tests/unit/other.tcl
Labels: major-decision-approved, rebranding, breaking-change, client-changes-needed

#1674 Implement: CLUSTER REPLICATE NO ONE
  src/cluster_legacy.c
  src/commands.def
  src/commands/cluster-replicate.json
  tests/unit/cluster/replica-detach.tcl
Labels: release-notes, major-decision-approved, needs-doc-pr

#1091 Trigger manual failover on SIGTERM / shutdown to cluster primary
  src/cluster.h
  src/cluster_legacy.c
  src/config.c
  src/replication.c
  src/server.c
  src/server.h
  tests/support/util.tcl
  tests/unit/cluster/auto-failover-on-shutdown.tcl
  tests/unit/cluster/cross-version-cluster.tcl
  valkey.conf
Labels: release-notes, major-decision-approved, run-extra-tests

#1873 Fix defrag crash when using FLUSHDB ASYNC in cluster mode
  src/lazyfree.c
  tests/unit/memefficiency.tcl
Labels: release-notes

#1945 Rebranding in security warning log
  src/networking.c
Labels: rebranding

#1934 Update function clusterNodeSetSlotBit() return type to void
  src/cluster_legacy.c
Labels: polish

#1811 Introduce MPTCP
  src/anet.c
  src/anet.h
  src/config.c
  src/server.c
  src/server.h
  tests/unit/introspection.tcl
  valkey.conf
Labels: release-notes, major-decision-approved

#1948 Fix panic in primary when blocking shutdown after previous block with timeout
  src/blocked.c
  tests/integration/shutdown.tcl
Labels: release-notes

#1777 Ignore stale gossip packets that arrive out of order
  src/cluster_legacy.c
  tests/cluster/cluster.tcl
  tests/support/cluster_util.tcl
Labels: release-notes, run-extra-tests

#1910 Add node pfail and fail count to cluster info metrics
  src/cluster_legacy.c
  tests/unit/cluster/info.tcl
Labels: cluster, major-decision-approved

#1904 Add sentinel_total_tilt to sentinel INFO sentinel
  src/sentinel.c
Labels: release-notes, major-decision-approved

#1952 Fix incorrect lag reported in XINFO GROUPS
  src/t_stream.c
  tests/unit/type/stream-cgroups.tcl
Labels: release-notes

#1819 Fix engine crash on module client blocking during keyspace events
  src/adlist.c
  src/bitops.c
  src/expire.c
  src/module.c
  src/module.h
  src/networking.c
  src/notify.c
  src/server.c
  src/server.h
  src/t_hash.c
  src/t_list.c
  src/t_set.c
  src/t_stream.c
  src/t_string.c
  src/t_zset.c
  tests/modules/Makefile
  tests/modules/auth.c
  tests/modules/block_keyspace_notification.c
  tests/unit/moduleapi/block_keyspace_notification.tcl
Labels: release-notes

#573 Avoid shard id update of replica if not matching with primary shard id
  src/cluster_legacy.c
  tests/support/cluster.tcl
  tests/unit/cluster/shardid-propagation.tcl
  tests/unit/cluster/slot-migration.tcl
Labels: cluster, release-notes, run-extra-tests

#1965 Fix CI latest fedora: install awk and tcl8, build tcltls from source
  .github/actions/rpm-distros-tcl8/action.yml
  .github/workflows/daily.yml
Labels: run-extra-tests

#2007 Convert pubsub dicts to hashtables
  src/acl.c
  src/defrag.c
  src/networking.c
  src/pubsub.c
  src/server.c
  src/server.h
Labels: run-extra-tests

#1961 Introduce MPTCP for replica
  src/anet.c
  src/anet.h
  src/cluster_legacy.c
  src/config.c
  src/connection.h
  src/rdma.c
  src/replication.c
  src/server.h
  src/socket.c
  src/tls.c
  tests/unit/introspection.tcl
  valkey.conf
Labels: release-notes, major-decision-approved
