Repository valkey-io/valkey, pull requests merged in 2025-07, with the labels that each got.

#2195 Add SAFE option to SHUTDOWN to reject shutdown in unsafe situations
  src/cluster.h
  src/cluster_legacy.c
  src/commands.def
  src/commands/shutdown.json
  src/config.c
  src/db.c
  src/server.c
  src/server.h
  tests/unit/cluster/shutdown.tcl
  valkey.conf
Labels: release-notes, major-decision-approved, needs-doc-pr

#1761 Implement rps control for benchmark using token bucket algorithm
  src/valkey-benchmark.c
Labels: to-be-merged, needs-doc-pr

#2288 Fix leak when shrinking a hashtable without entries
  src/hashtable.c
  tests/unit/expire.tcl
Labels: release-notes

#2283 Generate a new shard_id when the replica executes CLUSTER RESET SOFT
  src/cluster_legacy.c
  tests/unit/cluster/shardid-propagation.tcl
Labels: run-extra-tests

#2304 Make unit test report each memory leak only once
  src/unit/test_files.h
  src/unit/test_hashtable.c
  src/unit/test_main.c
  src/unit/test_rax.c
  src/unit/test_zmalloc.c
Labels: run-extra-tests

#2102 [valkey-benchmark] Allow multiple random (or sequential) placeholders and fix zadd --sequential to create expected data
  .config/typos.toml
  src/valkey-benchmark.c
  tests/integration/valkey-benchmark.tcl
Labels: release-notes

#2334 Change default values of valkey-cli to use valkey naming, and added fallback to old values
  src/valkey-cli.c
Labels: release-notes

#2301 Fix replica (the old primary) claims to sitll have slots after manual failover
  src/cluster_legacy.c
  src/debug.c
  src/server.c
  src/server.h
  tests/unit/cluster/manual-failover.tcl
Labels: run-extra-tests

#1920 Add support for automatic client authentication via TLS certificate fields
  src/acl.c
  src/config.c
  src/connection.h
  src/networking.c
  src/server.c
  src/server.h
  src/tls.c
  tests/unit/tls.tcl
  valkey.conf
Labels: major-decision-approved

#2286 Include command fullname in error message when returning NO_MULTI error
  src/server.c
  tests/unit/multi.tcl
Labels: release-notes, major-decision-approved, breaking-change

#2292 Auto-failover on shutdown unified config
  src/cluster.h
  src/cluster_legacy.c
  src/commands.def
  src/commands/shutdown.json
  src/config.c
  src/db.c
  src/server.c
  src/server.h
  tests/unit/cluster/auto-failover-on-shutdown.tcl
  tests/unit/cluster/cross-version-cluster.tcl
  valkey.conf
Labels: release-notes, major-decision-approved, needs-doc-pr

#2154 Limiting the new reconnections for failed nodes
  src/cluster_legacy.c
  src/cluster_legacy.h
  src/server.c
  src/server.h
Labels: cluster, run-extra-tests

#2379 Defrag should only skip non-existent dbs, not empty dbs
  src/defrag.c
Labels: run-extra-tests

#2277 Optimize cluster failure report
  src/cluster_legacy.c
  src/cluster_legacy.h
  tests/unit/cluster/failure-marking.tcl
Labels: cluster, run-extra-tests
