Repository valkey-io/valkey, pull requests merged in 2025-01, with the labels that each got.

#1449 Offload reading the replication stream to IO threads
  src/io_threads.c
  src/networking.c
  src/replication.c
  src/server.h
Labels: release-notes, run-extra-tests

#1499 Use the correct command proc for the LOOKUP_NOTOUCH exception in lookupKey
  src/db.c
  tests/unit/introspection-2.tcl
Labels: release-notes

#1512 Fix for when active rehashing kvstore dictionaries are replaced by defrag
  src/kvstore.c
Labels: release-notes

#1487 Add `availability_zone` to the HELLO response
  src/networking.c
  tests/unit/protocol.tcl
  tests/unit/tracking.tcl
Labels: release-notes, major-decision-approved, needs-doc-pr, client-changes-needed

#1405 client struct: lazy init components and optimize struct layout
  src/acl.c
  src/aof.c
  src/blocked.c
  src/cluster.c
  src/cluster_legacy.c
  src/module.c
  src/module.h
  src/multi.c
  src/networking.c
  src/pubsub.c
  src/rdb.c
  src/replication.c
  src/script.c
  src/server.c
  src/server.h
  src/timeout.c
  src/tracking.c
Labels: release-notes, run-extra-tests

#1427 Replace dict with new hashtable: sorted set datatype
  src/aof.c
  src/db.c
  src/debug.c
  src/defrag.c
  src/evict.c
  src/geo.c
  src/module.c
  src/object.c
  src/rdb.c
  src/server.c
  src/server.h
  src/sort.c
  src/t_zset.c
Labels: release-notes, run-extra-tests

#1501 Accelerate hash table iterator with prefetching
  src/hashtable.c
Labels: release-notes

#1541 Fix module LatencyAddSample still work when latency-monitor-threshold is 0
  src/module.c
  tests/modules/basics.c
  tests/unit/moduleapi/basics.tcl
Labels: release-notes

#1018 Do election in order based on failed primary rank to avoid voting conflicts
  src/cluster_legacy.c
  src/cluster_legacy.h
  tests/unit/cluster/failover2.tcl
Labels: release-notes, run-extra-tests

#1191 Mark the node as FAIL when the node is marked as NOADDR and broadcast the FAIL
  src/cluster_legacy.c
  tests/unit/cluster/noaddr.tcl
Labels: bug, cluster, release-notes, run-extra-tests

#1534 Add latency stats around cluster config file operations
  src/cluster_legacy.c
  tests/unit/latency-monitor.tcl
Labels: release-notes

#1545 Skip CLI tests with reply schema validation
  tests/integration/valkey-cli.tcl
Labels: test-failure, run-extra-tests

#1549 Test coverage for ECHO for reply schema validation
  .github/workflows/daily.yml
  tests/unit/other.tcl
Labels: test-failure, run-extra-tests

#1502 Replace dict with new hashtable: hash datatype
  src/aof.c
  src/db.c
  src/debug.c
  src/defrag.c
  src/lazyfree.c
  src/module.c
  src/object.c
  src/rdb.c
  src/server.c
  src/server.h
  src/t_hash.c
Labels: release-notes, run-extra-tests

#1553 Introduce const_sds for const-content sds
  src/sds.c
  src/sds.h
  src/server.c
  src/unit/test_sds.c
Labels: run-extra-tests

#1401 Adding Missing filters to CLIENT LIST and Dedup Parsing
  src/commands.def
  src/commands/client-caching.json
  src/commands/client-capa.json
  src/commands/client-getname.json
  src/commands/client-getredir.json
  src/commands/client-help.json
  src/commands/client-id.json
  src/commands/client-import-source.json
  src/commands/client-info.json
  src/commands/client-kill.json
  src/commands/client-list.json
  src/commands/client-no-evict.json
  src/commands/client-no-touch.json
  src/commands/client-pause.json
  src/commands/client-reply.json
  src/commands/client-setname.json
  src/commands/client-tracking.json
  src/commands/client-trackinginfo.json
  src/commands/client-unblock.json
  src/commands/client-unpause.json
  src/commands/client.json
  src/networking.c
  src/server.h
  tests/unit/introspection.tcl
Labels: release-notes, major-decision-approved, needs-doc-pr

#1517 Incr expired_keys if the expiration time is already expired
  src/db.c
  tests/unit/expire.tcl
  tests/unit/pubsub.tcl
Labels: release-notes, client-changes-needed

#1563 Fix cluster info sent stats for message with light header
  src/cluster_legacy.c
  tests/unit/cluster/pubsub.tcl
Labels: bug, cluster, release-notes

#1574 Fix memory leak in forgotten node ping ext code path
  src/cluster_legacy.c
Labels: bug

#1626 Fix use-after-free in hashtableTwoPhasePopDelete
  src/hashtable.c
Labels: test-failure

#1604 Relaxed RDB version check
  src/cluster.c
  src/config.c
  src/rdb.c
  src/rdb.h
  src/server.h
  tests/assets/encodings-rdb987.rdb
  tests/integration/rdb.tcl
  tests/unit/dump.tcl
  valkey.conf
Labels: release-notes, major-decision-approved
