Repository valkey-io/valkey, pull requests merged in 2025-02, with the labels that each got.

#1570 Extend LATENCY LATEST to add sum / cnt stats
  src/latency.c
  src/latency.h
  tests/unit/latency-monitor.tcl
Labels: release-notes, major-decision-approved, needs-doc-pr

#1479 skip CRC checksumming during diskless full sync with TLS enabled.
  src/connection.h
  src/rdb.c
  src/rdma.c
  src/replication.c
  src/rio.c
  src/rio.h
  src/server.h
  src/socket.c
  src/tls.c
  src/unix.c
  tests/integration/skip-rdb-checksum.tcl
Labels: release-notes

#1387 move clientCron onto a separate timer
  src/config.c
  src/server.c
  src/server.h
  tests/integration/replication.tcl
  tests/unit/moduleapi/hooks.tcl
  tests/unit/moduleapi/testrdb.tcl
  tests/unit/other.tcl
  valkey.conf
Labels: release-notes, needs-doc-pr

#1675 Fix memory usage check in test for embedded objects
  tests/unit/type/string.tcl
Labels: test-failure, run-extra-tests

#1678 Add reply schema for LATENCY-LATESTS new fields
  src/commands/latency-latest.json
Labels: run-extra-tests

#1564 Add paused_reason to INFO CLIENTS
  src/networking.c
  src/server.c
  src/server.h
  tests/unit/pause.tcl
Labels: release-notes, major-decision-approved, needs-doc-pr

#1687 Increase threshold for info.tcl even higher
  tests/unit/info.tcl
Labels: run-extra-tests

#1685 Disable mem usage test case for non-jemalloc allocators
  src/object.c
  tests/unit/type/string.tcl
Labels: test-failure, run-extra-tests

#1497 Adds support for running `EVAL` with different scripting engines
  cmake/Modules/SourceFiles.cmake
  src/Makefile
  src/defrag.c
  src/eval.c
  src/eval.h
  src/functions.c
  src/functions.h
  src/lazyfree.c
  src/lua/debug_lua.c
  src/lua/debug_lua.h
  src/lua/engine_lua.c
  src/lua/engine_lua.h
  src/lua/function_lua.c
  src/lua/function_lua.h
  src/lua/script_lua.c
  src/lua/script_lua.h
  src/module.c
  src/scripting_engine.c
  src/scripting_engine.h
  src/server.c
  src/server.h
  src/valkeymodule.h
  tests/modules/helloscripting.c
  tests/unit/functions.tcl
  tests/unit/moduleapi/scriptingengine.tcl
  tests/unit/scripting.tcl
Labels: run-extra-tests

#1696 Fix outdated slot info comments in clusterGenNodesSlotsInfo
  src/cluster_legacy.c
Labels: polish

#1582 Add support for MustObeyClient Module API
  src/module.c
  src/valkeymodule.h
  tests/modules/propagate.c
  tests/unit/moduleapi/propagate.tcl
Labels: major-decision-approved

#1694 valkey-cli: re-select previously selected database after reconnect
  src/valkey-cli.c
  tests/integration/valkey-cli.tcl
Labels: bug, release-notes

#1710 Fix new benchmark test under the TLS
  src/valkey-benchmark.c
  tests/integration/valkey-benchmark.tcl
Labels: run-extra-tests

#1723 Introduce valkey_version_full info field which includes the release stage
  src/server.c
  src/version.h
Labels: release-notes

#1738 Add a daily test running for ARM
  .github/workflows/daily.yml
Labels: run-extra-tests

#1357 Add new module API flag to bypass command validation
  src/module.c
  src/valkeymodule.h
  tests/modules/datatype2.c
  tests/modules/propagate.c
Labels: major-decision-pending, needs-doc-pr

#1737 Fix error "SSL routines::bad length" when connTLSWrite is called second time with smaller buffer
  src/tls.c
Labels: bug, release-notes, run-extra-tests

#1748 Fix murmur32 on large strings
  deps/lua/src/lstring.c
Labels: bug

#1769 Disable Fedora Fawhide in Daily runs
  .github/workflows/daily.yml
Labels: run-extra-tests

#1767 Add large memory flag for asan tests
  .github/workflows/daily.yml
Labels: run-extra-tests

#1773 Fixed active-expire-effort description in conf file
  valkey.conf
Labels: polish

#1579 Embed hash value in hash type entry
  src/object.c
  src/sds.h
  src/server.h
  src/t_hash.c
Labels: run-extra-tests

#1763 Enable TCP_NODELAY by default in incoming and outgoing connections
  src/anet.c
  src/cluster.c
  src/cluster_legacy.c
  src/connection.h
  src/replication.c
  src/socket.c
  src/tls.c
Labels: release-notes

#1741 Optimize bitcount command by SIMD
  src/bitops.c
  src/unit/test_bitops.c
  src/unit/test_files.h
Labels: release-notes, performance

#1785 Remove unicode optimization in Lua cjson library
  deps/lua/src/lua_cjson.c
Labels: run-extra-tests

#1686 Add Cluster Bus Port out of range error message for Cluster Meet command
  src/cluster_legacy.c
Labels: release-notes

#1690 Add cluster-manual-failover-timeout to configure the timeout for manual failover
  src/cluster.h
  src/cluster_legacy.c
  src/cluster_legacy.h
  src/config.c
  src/server.h
  valkey.conf
Labels: release-notes, major-decision-approved, needs-doc-pr
