Repository valkey-io/valkey, pull requests merged in 2025-05, with the labels that each got.

#1859 Hyperloglog ARM NEON SIMD optimization
  src/hyperloglog.c
Labels: release-notes

#2036 Properly escape double quotes and backslash in sdscatrepr
  src/sds.c
  tests/unit/introspection.tcl
Labels: to-be-merged

#1671 Add multi-database support to cluster mode
  src/cluster.c
  src/cluster.h
  src/cluster_legacy.c
  src/config.c
  src/db.c
  src/server.c
  src/server.h
  src/valkey-benchmark.c
  src/valkey-cli.c
  tests/support/cluster_util.tcl
  tests/unit/cluster/cli.tcl
  tests/unit/cluster/multidb.tcl
  tests/unit/cluster/slot-migration.tcl
  tests/unit/introspection.tcl
  valkey.conf
Labels: release-notes, to-be-merged, needs-doc-pr, client-changes-needed

#1995 Environment variable REDISCLI_AUTH to VALKEYCLI_AUTH conversion
  src/valkey-cli.c
Labels: release-notes, rebranding

#2025 Compile with -Wundef
  CMakeLists.txt
  src/Makefile
  src/config.h
  src/crcspeed.c
  src/debug.c
  src/lzfP.h
  src/rdma.c
  src/rio.c
  src/sentinel.c
  src/setproctitle.c
  src/tls.c
Labels: run-extra-tests

#2046 valkey-cli: Count databases correctly in --cluster subcommands
  src/valkey-cli.c
Labels: run-extra-tests

#2052 Restore omitted singledb config in tests
  tests/unit/cluster/cli.tcl
Labels: run-extra-tests

#2050 Use the correct port for migration
  tests/unit/cluster/slot-migration.tcl
Labels: test-failure, run-extra-tests

#1966 Disallowing Client Reply is On / Off / Skip when Client is Multi
  src/server.c
  tests/unit/multi.tcl
Labels: release-notes, breaking-change

#2056 Prevent tests setting singledb from breaking other tests
  tests/README.md
  tests/integration/aof.tcl
  tests/support/server.tcl
  tests/support/test.tcl
  tests/test_helper.tcl
  tests/unit/cluster/base.tcl
  tests/unit/cluster/cli.tcl
  tests/unit/cluster/cluster-multiple-meets.tcl
  tests/unit/cluster/cluster-reliable-meet.tcl
  tests/unit/cluster/cross-version-cluster.tcl
  tests/unit/cluster/failure-marking.tcl
  tests/unit/cluster/shardid-propagation.tcl
  tests/unit/moduleapi/cross-version-cluster.tcl
Labels: run-extra-tests

#2030 Optimize findBucket performance using SIMD
  src/config.h
  src/hashtable.c
Labels: release-notes

#2059 Support RDMA for valkey-cli and benchmark
  cmake/Modules/ValkeySetup.cmake
  deps/CMakeLists.txt
  deps/Makefile
  src/Makefile
  src/cli_common.c
  src/cli_common.h
  src/valkey-benchmark.c
  src/valkey-cli.c
Labels: release-notes, needs-doc-pr

#2067 Support MPTCP for valkey-cli and benchmark
  src/cli_common.c
  src/cli_common.h
  src/valkey-benchmark.c
  src/valkey-cli.c
Labels: release-notes

#2068 valkey-cli: remove RESP version assertion from getDatabases()
  src/valkey-cli.c
Labels: run-extra-tests

#1867 Optimize BITCOUNT using ARM NEON SIMD
  src/bitops.c
  src/unit/test_bitops.c
Labels: release-notes, performance

#2057 valkey-benchmark: Arbitrary command sequence
  src/valkey-benchmark.c
  tests/integration/valkey-benchmark.tcl
Labels: release-notes

#2063 Make sure that the same point reports for geo comparisons
  src/geohash_helper.c
  tests/unit/geo.tcl
Labels: run-extra-tests

#2081 Reverting the panic() introduced in #2027
  src/listpack.c
Labels: run-extra-tests

#2080 Redundant Calculation of mstime()
  src/cluster_legacy.c
Labels: run-extra-tests

#2091 Fix minor memory leak in valkey-cli when command table hint fails due to NOAUTH
  src/valkey-cli.c
  tests/integration/valkey-cli.tcl
Labels: run-extra-tests

#2098 Allow mixing quoted and unquoted inline args
  src/sds.c
  src/unit/test_sds.c
  tests/integration/valkey-cli.tcl
  tests/unit/protocol.tcl
Labels: release-notes

#1725 Respect process umask when creating data files
  .github/workflows/codecov.yml
  src/aof.c
  src/replication.c
  tests/integration/rdb.tcl
Labels: release-notes

#1975 Add DELIFEQ command
  src/commands.def
  src/commands/delifeq.json
  src/server.h
  src/t_string.c
  tests/unit/type/string.tcl
Labels: release-notes, major-decision-approved, needs-doc-pr, client-changes-needed

#2126 Fix UBSAN run for hashtable unittest
  src/unit/test_hashtable.c
Labels: test-failure, run-extra-tests

#2123 Make Tclx optional in tests (fix Daily failure)
  tests/integration/rdb.tcl
Labels: test-failure, run-extra-tests

#2133 Fix the GNU IFUNC error in alpine (non-glibc) environment
  src/config.h
Labels: run-extra-tests

#2132 Free module context even if there was no content written in auxsave2
  src/rdb.c
Labels: to-be-merged

#1838 Replication Flow Control – Prioritizing replication traffic in the replica
  src/networking.c
Labels: release-notes, major-decision-approved

#2144 Correctly cast the extension lengths
  src/cluster_legacy.c
Labels: release-notes
