Repository valkey-io/valkey, pull requests merged in 2025-09, with the labels that each got.

#2215 Remove deny_blocking check in moduleBlockClient, cleanup code and doc
  src/module.c
  src/module.h
  tests/modules/auth.c
Labels: run-extra-tests

#2615 Fix memory leak in deferred reply buffer
  src/networking.c
Labels: bug

#2629 Fix test that checks `extended-redis-compatibility` config deprecation rules
  tests/unit/other.tcl
Labels: bug

#2631 Optimize skiplist random level generation logic
  src/server.h
  src/t_zset.c
Labels: release-notes, performance
